### ISSUE TITLE
KO generator doesn't give me an option to choose language

### ISSUE THREAD

**Issue by ganeshvittal** [SteveSanderson/generator-ko#18]
Hi Steve,

In your demo, while generating the scaffolding using Yoemen, there was an option to choose Language option; either javascript or Typescript. But when I generate the ko, it doesn't provide me any language option. It generates typescript by default. Can you please let me know why this happens?

**Comment by nenitiko** [comment]
These options were removed in favor of ES6 or ES2015 (http://www.ecma-international.org/ecma-262/6.0/). The generator uses a gulp task and a library (babel-core) to transform (transpile) from ES6 to a Javascript that will be understood by most modern browsers (since not all of them are still up to speed with the latest ES6 features.)

You can still use Typescript, but you may have to change the gulp files, or play with the Typescript configuration. Typescript can generate both ES6 and plan JS, it all depends what your needs are. The trend I'm seeing now is to adopt and consume ES6, and use TypeScript as an add-on if you really want its static type-checking capabilities and language features not in ES6.

**Comment by bakersoft** [comment]
The problem I have here is that I have js files being generated with TypeScript in them. During his demo, when choosing JavaScript, it generated js files with JavaScript in them which is what I would expect to see. Is anyone else seeing this same behavior? If so, is there some steps than can be executed to work around this?

**Comment by bakersoft** [comment]
The problem I have now with this is the resulting code in the js file cannot be executed by the browser. startup.js for example generates:

import 'jquery';
import 'bootstrap';
import ko from 'knockout';

which immediately throws an error in Chrome (syntax error). Are there some new steps that have to be taken to get actual JavaScript generating in these js files so the browser can actually execute them?

**Comment by nenitiko** [comment]
This is ES6 code, not for direct browser consumption (for now) but to be pre-processed by "babel" (https://babeljs.io/) the gulpfile.js has a section (or task) called js:babel which converts (transpiles/compiles) from ES6 to browser-understendable JavaScript. ES6 is the future (or the present?) of JavaScript and most of modern libraries and tools use it extensively including generator-knockout.

In order for your startup.js to be "transpiled" you must serve your code from the "dist" folder, which is copied transpiled/bundled and minified by running **gulp** and then **gulp serve:dist**, or from the src folder which is dynamically transpiled by the "connect" server by running the the **gulp serve:src** task.

**Comment by carbontwelve** [comment]
I use `gulp serve:src` for development with this and have no issues.

**Comment by SteveSanderson** [comment]
As per @nenitiko's comments, this generator produces ES2015 only now (which is not TypeScript, BTW).
